output "naming_base_name" {
  description = "Canonical base name generated by naming module."
  value       = module.naming.base_name
}

output "naming_region_short" {
  description = "Short region code resolved by naming module."
  value       = module.naming.region_short
}

output "resource_group_id" {
  description = "Resource Group ID."
  value       = module.resource_group.id
}

output "resource_group_name" {
  description = "Resource Group name."
  value       = module.resource_group.name
}

output "resource_group_location" {
  description = "Resource Group location."
  value       = module.resource_group.location
}

output "vnet_id" {
  description = "Virtual Network resource ID."
  value       = module.network.vnet_id
}

output "vnet_name" {
  description = "Virtual Network name."
  value       = module.network.vnet_name
}

output "subnet_ids" {
  description = "Subnet IDs keyed by subnet key."
  value       = module.network.subnet_ids
}

output "nsg_function_integration_id" {
  description = "NSG ID associated with function integration subnet."
  value       = module.nsg_function_integration.id
}

output "nsg_management_id" {
  description = "NSG ID associated with management subnet."
  value       = module.nsg_management.id
}

output "private_dns_zone_ids" {
  description = "Private DNS zone IDs keyed by logical zone key."
  value       = module.private_dns.zone_ids
}

output "private_dns_vnet_link_ids" {
  description = "Private DNS VNet link IDs keyed by '<zone_key>|<vnet_id>'."
  value       = module.private_dns.vnet_link_ids
}

output "storage_account_id" {
  description = "Storage account resource ID."
  value       = module.storage.storage_account_id
}

output "storage_account_name" {
  description = "Storage account name."
  value       = module.storage.storage_account_name
}

output "storage_blob_service_uri" {
  description = "Storage blob service URI."
  value       = module.storage.blob_service_uri
}

output "digital_twins_id" {
  description = "Azure Digital Twins resource ID."
  value       = module.digital_twins.id
}

output "digital_twins_name" {
  description = "Azure Digital Twins instance name."
  value       = module.digital_twins.name
}

output "digital_twins_host_name" {
  description = "Azure Digital Twins host name."
  value       = module.digital_twins.host_name
}

output "function_app_id" {
  description = "Function Flex app ID."
  value       = module.function_flex.function_app_id
}

output "function_app_principal_id" {
  description = "Function Flex managed identity principal ID."
  value       = module.function_flex.function_app_principal_id
}

output "rbac_role_assignment_ids" {
  description = "RBAC role assignment IDs keyed by assignment key."
  value       = module.rbac.role_assignment_ids
}

output "log_analytics_workspace_id" {
  description = "Log Analytics workspace ID."
  value       = module.observability_core.log_analytics_workspace_id
}

output "application_insights_id" {
  description = "Application Insights resource ID."
  value       = module.observability_core.application_insights_id
}

output "diagnostic_setting_ids" {
  description = "Diagnostic setting IDs keyed by target key."
  value       = module.diagnostic_settings.diagnostic_setting_ids
}

output "dashboard_workbook_id" {
  description = "Operations workbook resource ID."
  value       = module.dashboard_workbook.id
}
