output "naming_base_name" {
  description = "Canonical base name generated by naming module."
  value       = module.naming.base_name
}

output "naming_region_short" {
  description = "Short region code resolved by naming module."
  value       = module.naming.region_short
}

output "resource_group_id" {
  description = "Resource Group ID."
  value       = module.resource_group.id
}

output "resource_group_name" {
  description = "Resource Group name."
  value       = module.resource_group.name
}

output "resource_group_location" {
  description = "Resource Group location."
  value       = module.resource_group.location
}

output "vnet_id" {
  description = "Virtual Network resource ID."
  value       = module.network.vnet_id
}

output "vnet_name" {
  description = "Virtual Network name."
  value       = module.network.vnet_name
}

output "subnet_ids" {
  description = "Subnet IDs keyed by subnet key."
  value       = module.network.subnet_ids
}

output "private_dns_zone_ids" {
  description = "Private DNS zone IDs keyed by logical zone key."
  value       = module.private_dns.zone_ids
}

output "private_dns_vnet_link_ids" {
  description = "Private DNS VNet link IDs keyed by '<zone_key>|<vnet_id>'."
  value       = module.private_dns.vnet_link_ids
}

output "storage_account_id" {
  description = "Storage account resource ID."
  value       = module.storage.storage_account_id
}

output "storage_account_name" {
  description = "Storage account name."
  value       = module.storage.storage_account_name
}

output "storage_blob_service_uri" {
  description = "Storage blob service URI."
  value       = module.storage.blob_service_uri
}

output "eventhub_namespace_name" {
  description = "Event Hubs namespace name."
  value       = module.event_hub.namespace_name
}

output "eventhub_name" {
  description = "Ingestion Event Hub name."
  value       = module.event_hub.eventhub_name
}

output "function_app_id" {
  description = "Function Flex app ID."
  value       = module.function_flex.function_app_id
}

output "function_app_principal_id" {
  description = "Function Flex managed identity principal ID."
  value       = module.function_flex.function_app_principal_id
}
