output "naming_base_name" {
  description = "Canonical base name generated by naming module."
  value       = module.naming.base_name
}

output "naming_region_short" {
  description = "Short region code resolved by naming module."
  value       = module.naming.region_short
}

output "resource_group_id" {
  description = "Resource Group ID."
  value       = module.resource_group.id
}

output "resource_group_name" {
  description = "Resource Group name."
  value       = module.resource_group.name
}

output "resource_group_location" {
  description = "Resource Group location."
  value       = module.resource_group.location
}

output "vnet_id" {
  description = "Virtual Network resource ID."
  value       = module.network.vnet_id
}

output "vnet_name" {
  description = "Virtual Network name."
  value       = module.network.vnet_name
}

output "subnet_ids" {
  description = "Subnet IDs keyed by subnet key."
  value       = module.network.subnet_ids
}
